
try:
    print("2" + 2)
except Exception as e:
    print("Found exception:")
    print(e)

# print("2" + 2)

print("Hello")